language: java
sudo: false
install: true

addons:
  sonarqube:
    token:
      secure: "qF/bdTJxQkY/NOqafux/PZeSG4ZvtzwpxSTR9ZE7wyxAO/6YEJQsu1lA0giJkDo1ZyFcoL6XXzSgFX2bfkMvX+ubnPXZh4zg3iVJ748ta2NGxR7NpoBEGeI+bTljsoaVtoG+xY8reUeySUOaupJuINIrgUll+k1XdoYv1t8BD/yEpAcyzOh0SF+kgANUJNP4sdiAgHa+hClcnAI6EjFdnx0rZSKGK3fXRzphp38J7lESKubAHd+Xf3P4zcttMNy+LZgCXWpS54d7OLnrpm907qB/OyStc+yih8iBungCfXNfaiL5uL9b4WW7zzgS/IMezzvPg4/cR/o8KJmcVbi7kPEBaNdvenjD3RKlvJOOnr43MtGrc8nS7AnZw/BA32uSSWqV4TMOb75SDnNSkosM1Me0Kp3euJKVenx+snhcfKjwHDAZjxTVr46dCXkaxmCC5Bg+442OGILLHKC3ASgWUuYR3cSB3jp7OGGT+VGLaRM+/tA206cJYAYn7w7gSjfP16uL3JNTgCeBKUparvMrJ/jywzYGoCzSxDuZNAGREd0OFXnUSTE47nhIXZubIvFokefrt5k132sg3BzUImpIt5IuzU7BDKbeEhPWqiL6ll0QtJDFcJ/RSmvxvSitnKIIQ26eFU5CTK1FN03HOX9YY+lrMv0N7SmTQqCGVCMHsAs="

jdk:
- oraclejdk8

script:
- "./gradlew sonarqube"

before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
  - "$HOME/.gradle"
  - ".gradle"
